const DBKEY='certibox_app_v3_qr';
let recipientSession=null,courierEvent=null,courierTimer=null,reqTimer=null,qrScanner=null;
function db(){return JSON.parse(localStorage.getItem(DBKEY)||'{"boxes":{},"events":{},"couriers":{}}')}
function save(x){localStorage.setItem(DBKEY,JSON.stringify(x))}
function now(){return new Date().toISOString()}
function uid(){return 'EVT-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}
function esc(s){return String(s||'').replace(/[<>&"]/g,m=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[m]))}
function fmt(v){return v?new Date(v).toLocaleString('it-IT'):'-'}
function label(s){return {pending:'IN ATTESA',authorized:'DEPOSITO AUTORIZZATO',refused:'RIFIUTATO',expired:'SCADUTO'}[s]||s}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));let k=id.includes('courier')?'courier':id.includes('recipient')?'recipient':id==='settings'?'settings':'home';let n=document.getElementById('n-'+k);if(n)n.classList.add('active')}
(function(){const d=db();if(!d.boxes['BOX-0001'])d.boxes['BOX-0001']={box:'BOX-0001',owner:'Hamza Ryah',pin:'1234',rule:'manual',notifications:true,autoReceipt:true,quietMode:false,trustedCouriers:'',blockedCouriers:'',createdAt:now()};if(!d.couriers['POSTE-BG-01'])d.couriers['POSTE-BG-01']={code:'POSTE-BG-01',password:'1234',name:'Poste Italiane - BG'};save(d);const p=new URLSearchParams(location.search),box=p.get('box');if(box){startCourier();courierBox.value=box.toUpperCase()}})();
function startCourier(){show('courierLogin');courierCodeLogin.value=localStorage.getItem('courierCode')||'';courierPassLogin.value=localStorage.getItem('courierPass')||''}
function loginCourier(){const code=courierCodeLogin.value.trim().toUpperCase(),pass=courierPassLogin.value.trim();const c=db().couriers[code];if(!c||c.password!==pass){courierLoginOut.innerHTML='<div class="danger">Credenziali non valide. Demo: POSTE-BG-01 / 1234</div>';return}if(rememberCourier.checked){localStorage.setItem('courierCode',code);localStorage.setItem('courierPass',pass)}courierCode.value=code;show('courierArea')}
function normalizeQR(t){t=String(t||'').trim();try{const u=new URL(t);const b=u.searchParams.get('box');if(b)return b.toUpperCase()}catch(e){}const m=t.match(/BOX[-_ ]?[A-Z0-9]+/i);return m?m[0].replace(/\s/g,'').replace('_','-').toUpperCase():t.toUpperCase()}
async function openCamera(){const reader=document.getElementById('qr-reader'),out=document.getElementById('scanOut');reader.style.display='block';out.innerHTML='<div class="warn">Avvio scanner QR...</div>';if(typeof Html5Qrcode==='undefined'){out.innerHTML='<div class="danger">Motore QR non caricato. Ricarica la pagina con internet attivo.</div>';return}try{if(qrScanner){try{await qrScanner.stop()}catch(e){}try{qrScanner.clear()}catch(e){}}qrScanner=new Html5Qrcode('qr-reader');await qrScanner.start({facingMode:'environment'},{fps:10,qrbox:{width:240,height:240}},async text=>{const box=normalizeQR(text);courierBox.value=box;out.innerHTML='<div class="ok">QR letto: '+esc(box)+'</div>';await stopScanner()},()=>{})}catch(e){out.innerHTML='<div class="danger">Camera non disponibile o permesso negato.</div>'}}
async function stopScanner(){if(qrScanner){try{await qrScanner.stop()}catch(e){}try{qrScanner.clear()}catch(e){}}document.getElementById('qr-reader').style.display='none'}
function useDemoQR(){courierBox.value='BOX-0001';stopScanner();scanOut.innerHTML='<div class="ok">QR demo letto: BOX-0001</div>'}
function sendRequest(){const box=courierBox.value.trim().toUpperCase(),code=courierCode.value.trim().toUpperCase(),tr=tracking.value.trim(),type=deliveryType.value;const d=db(),b=d.boxes[box];if(!b){courierOut.innerHTML='<div class="danger">Box non trovata.</div>';return}if(!code||!tr){alert('Inserisci operatore e tracking');return}const ev={id:uid(),box,owner:b.owner,courierCode:code,tracking:tr,type,status:'pending',createdAt:now(),expiresAt:Date.now()+60000};d.events[ev.id]=ev;save(d);courierEvent=ev.id;renderCourierStatus();if(courierTimer)clearInterval(courierTimer);courierTimer=setInterval(renderCourierStatus,1000)}
function renderCourierStatus(){const d=db(),ev=d.events[courierEvent];if(!ev)return;if(ev.status==='pending'&&Date.now()>ev.expiresAt){ev.status='expired';ev.decidedAt=now();d.events[ev.id]=ev;save(d)}const rem=Math.max(0,Math.ceil((ev.expiresAt-Date.now())/1000));courierOut.innerHTML='<div class="'+(ev.status==='authorized'?'ok':ev.status==='pending'?'warn':'danger')+'"><h2>'+label(ev.status)+'</h2><p>Tracking: '+esc(ev.tracking)+'</p>'+(ev.status==='pending'?'<div class="timer">'+rem+'</div><p>Attendi autorizzazione destinatario.</p>':'<p>'+(ev.status==='authorized'?'Procedi al deposito del plico.':'Non procedere al deposito.')+'</p><button class="dark" onclick="openReceipt(db().events[\\''+ev.id+'\\'])">Ricevuta</button>')+'</div>';if(ev.status!=='pending'&&courierTimer)clearInterval(courierTimer)}
function startRecipient(){show('recipientLogin')}
function saveBox(){const box=boxId.value.trim().toUpperCase(),owner=ownerName.value.trim(),pin=boxPin.value.trim();if(!box||!owner||!pin){alert('Compila ID Box, nome e PIN');return}const d=db();d.boxes[box]={box,owner,pin,rule:'manual',notifications:true,autoReceipt:true,quietMode:false,trustedCouriers:'',blockedCouriers:'',createdAt:now()};save(d);const link=location.origin+location.pathname+'?box='+encodeURIComponent(box);newBoxOut.innerHTML='<div class="ok"><b>Box attivata.</b><div class="qrbox"><div class="qr">QR</div><div class="code">'+link+'</div></div></div>';recipientBox.value=box;recipientPin.value=pin}
function loginRecipient(){const box=recipientBox.value.trim().toUpperCase(),pin=recipientPin.value.trim();const b=db().boxes[box];if(!b||b.pin!==pin){recipientLoginOut.innerHTML='<div class="danger">Accesso negato. Demo: BOX-0001 / 1234</div>';return}recipientSession=box;show('recipientArea');if(reqTimer)clearInterval(reqTimer);renderRecipientHome();reqTimer=setInterval(renderRecipientHome,1000)}
function renderRecipientHome(){if(!recipientSession)return;const d=db(),b=d.boxes[recipientSession];Object.values(d.events).forEach(ev=>{if(ev.status==='pending'&&Date.now()>ev.expiresAt){ev.status='expired';ev.decidedAt=now();d.events[ev.id]=ev}});save(d);const pending=Object.values(d.events).filter(e=>e.box===recipientSession&&e.status==='pending').sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const all=Object.values(d.events).filter(e=>e.box===recipientSession).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,5);if(pending.length){const ev=pending[0],rem=Math.max(0,Math.ceil((ev.expiresAt-Date.now())/1000));recipientPanel.innerHTML='<div class="danger"><h2>Autorizzazione richiesta</h2><p><b>'+esc(ev.courierCode)+'</b><br>Tracking: '+esc(ev.tracking)+'<br>Tipo: '+esc(ev.type)+'</p><div class="timer">'+rem+'</div><button class="green" onclick="decide(\\''+ev.id+'\\',\\'authorized\\')">AUTORIZZA DEPOSITO</button><button class="red" onclick="decide(\\''+ev.id+'\\',\\'refused\\')">RIFIUTA</button></div>'}else{recipientPanel.innerHTML='<div class="ok"><h2>Nessuna richiesta in attesa</h2><p>Box: <b>'+esc(b.box)+'</b><br>Destinatario: '+esc(b.owner)+'</p></div><div class="grid"><button onclick="show(\\'settings\\')">Impostazioni</button><button class="dark" onclick="document.getElementById(\\'recipientHistoryCard\\').scrollIntoView({behavior:\\'smooth\\'})">Storico</button></div>'}recipientHistory.innerHTML=all.map(ev=>'<div class="item"><b>'+label(ev.status)+'</b><br>'+esc(ev.courierCode)+' • '+esc(ev.tracking)+'<br>'+fmt(ev.createdAt)+'<button class="dark" onclick="openReceipt(db().events[\\''+ev.id+'\\'])">Ricevuta</button></div>').join('')||'<div class="warn">Nessuno storico.</div>'}
function decide(id,status){const d=db(),ev=d.events[id];ev.status=status;ev.decidedAt=now();d.events[id]=ev;save(d);renderRecipientHome();openReceipt(ev)}
function loadSettingsFromSession(){if(!recipientSession){settingsOut.innerHTML='<div class="danger">Accedi prima come destinatario.</div>';return}const b=db().boxes[recipientSession];settingsOut.innerHTML='<div class="ok"><b>'+esc(b.box)+'</b> caricato.</div><label class="toggle">Notifiche richieste <input id="stNot" type="checkbox" '+(b.notifications!==false?'checked':'')+'></label><label class="toggle">Ricevuta automatica <input id="stRec" type="checkbox" '+(b.autoReceipt!==false?'checked':'')+'></label><label class="toggle">Modalità silenziosa <input id="stQuiet" type="checkbox" '+(b.quietMode?'checked':'')+'></label><select id="stRule"><option value="manual">Chiedi sempre</option><option value="always_authorize">Autorizza sempre</option><option value="always_refuse">Rifiuta sempre</option></select><input id="trusted" placeholder="Corrieri fidati, separati da virgola" value="'+esc(b.trustedCouriers||'')+'"><input id="blocked" placeholder="Corrieri bloccati, separati da virgola" value="'+esc(b.blockedCouriers||'')+'"><button onclick="saveSettings()">Salva impostazioni</button>';stRule.value=b.rule||'manual'}
function saveSettings(){const d=db(),b=d.boxes[recipientSession];b.notifications=stNot.checked;b.autoReceipt=stRec.checked;b.quietMode=stQuiet.checked;b.rule=stRule.value;b.trustedCouriers=trusted.value;b.blockedCouriers=blocked.value;d.boxes[recipientSession]=b;save(d);settingsOut.innerHTML='<div class="ok">Impostazioni salvate.</div>'}
function openReceipt(ev){receiptOut.innerHTML='<div class="receipt"><h2>CertiBox Delivery Receipt</h2><p>Registro autorizzazione deposito</p><div class="kv"><b>ID evento</b><span>'+esc(ev.id)+'</span></div><div class="kv"><b>Box</b><span>'+esc(ev.box)+'</span></div><div class="kv"><b>Destinatario</b><span>'+esc(ev.owner)+'</span></div><div class="kv"><b>Operatore</b><span>'+esc(ev.courierCode)+'</span></div><div class="kv"><b>Tracking</b><span>'+esc(ev.tracking)+'</span></div><div class="kv"><b>Tipo</b><span>'+esc(ev.type)+'</span></div><div class="kv"><b>Richiesta</b><span>'+fmt(ev.createdAt)+'</span></div><div class="kv"><b>Decisione</b><span>'+fmt(ev.decidedAt)+'</span></div><div class="kv"><b>Esito</b><span>'+label(ev.status)+'</span></div></div>';show('receipt')}
